export const NAVIGATION_MENU_OPTIONS = ['home', 'profile', 'works', 'contact']
export const THEME_OPTIONS = ['light', 'dark']
export const COLOR_OPTIONS = ['green', 'yellow', 'pink', 'purple', 'blue']
export const LEVEL_OPTIONS = ['novice', 'intermediate', 'advanced']
export const SUMMARY_OPTIONS = ['work', 'employment', 'education']
export const INPUT_TYPE_OPTIONS = ['text', 'number', 'email', 'password', 'checkbox']
